imu_filter_madgwick:
  ros__parameters:
    stateless: false
    use_mag: false
    publish_tf: true
    reverse_tf: false
    fixed_frame: "camera_link"
    constant_dt: 0.005
    publish_debug_topics: false
    world_frame: "enu"
    gain: 0.05
    zeta: 0.0
    mag_bias_x: 0.0
    mag_bias_y: 0.0
    mag_bias_z: 0.0
    orientation_stddev: 1.0
